### ISSUE TITLE
Pop up froze after entering username/password

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/vets-api#460] opened 2016-11-07 15:26 UTC
I do not know if this is a vets-website or vets-api issue, nor can I consistently reproduce it but it has happened once Friday and now once this morning. 

On staging at 10:20AM Eastern this morning, after entering my username and password (before any 2FA prompt), the login popup window stayed open like this indefinitely: 

![screen shot 2016-11-07 at 10 20 25 am](https://cloud.githubusercontent.com/assets/4719765/20063140/12ebb950-a4d4-11e6-9583-29d5b0959cde.png)

When I closed the window and refreshed the page, I was not logged in. 

I then tried logging in again, which worked successfully (didn't ask for username/password probably because i just entered it a couple minutes before, but did ask for 2FA).

**Comment by jcmeloni** [comment] 2016-11-07 15:28
I've seen this intermittently (< 5% of the time?) and with dev tools up it looks like something in the list is 302'ing.  Like Alex said, trying to login again always works.

**Comment by aub** [comment] 2016-11-07 15:44
Saw this error when it failed:

<img width="976" alt="screen shot 2016-11-07 at 10 43 37 am" src="https://cloud.githubusercontent.com/assets/2895/20064025/3383ffbc-a4d7-11e6-8ef5-e08c550ac3bb.png">

**Comment by omgitsbillryan** [comment] 2016-11-07 15:48
The url from the screenshot:

https://staging.vets.gov/auth/login/callback?token=9CxMn...

comes the final step of a successful login from the `vets-api` perspective:
```ruby
redirect_to SAML_CONFIG['relay'] + '?token=' + @session.token
```

**Comment by ayaleloehr** [comment] 2016-11-07 22:29
For tracking purposes, this happened again in dev at 5:26PM eastern today.

**Comment by omgitsbillryan** [comment] 2016-11-07 23:55
I was able to root cause to a XHR request race condition. If the response from `/v0/user` beats the response from `/sessions/new?level=3` then the `state.verifyUrl` is read before it is ever set.  

**Inside AuthApp.jsx (psuedo)**
```javascript
  componentDidMount() {
    if (__BUILDTYPE__ !== 'production') {
      this.serverRequest = $.get(`${environment.API_URL}/v0/sessions/new?level=3`, result => {
        this.setState({ verifyUrl: result.authenticate_via_get });
      });
    }

    this.checkUserLevel();
  }

  checkUserLevel() {
    ...
    fetch(`${environment.API_URL}/v0/user`, {
      method: 'GET'
    }).then(json => {
      ...
      window.location.href = this.state.verifyUrl;
      ...
    });
  }

```

Assigning to to @crwallace.

**Comment by jcmeloni** [comment] 2016-11-08 14:21
Good find, @omgitsbillryan !

**Comment by crwallace** [comment] 2016-11-08 15:10
Thanks everyone! We will address this today.

**Comment by plusjeff** [comment] 2016-11-09 22:19
(Will move to vets-website)

**Comment by jcmeloni** [comment] 2016-11-10 03:05
Moved to https://github.com/department-of-veterans-affairs/vets-website/issues/3887

**Closed by jcmeloni** 2016-11-10 03:05 UTC
Labels: 2-in-progress, bug, high-priority, Identity, launch-blocker
