### ISSUE TITLE
Noticed some header issues for log in area

### ISSUE THREAD

**Issue by J-Quag** [department-of-veterans-affairs/vets-api#459] opened 2016-11-07 14:28 UTC
Just noticed that the name no longer shows up and the profile/sign out links are now in white space and not part of the header. 

![image](https://cloud.githubusercontent.com/assets/15879513/20061122/70e1b7e2-a4cc-11e6-8719-e8825b5d2033.png)

**Comment by jcmeloni** [comment] 2016-11-07 14:54
@crwallace Want me to xfer to vets-website and tag Vanguard?  Not sure if there's anything on the API side here.

**Comment by ayaleloehr** [comment] 2016-11-07 14:58
duplicate of https://github.com/department-of-veterans-affairs/vets-website/issues/3761

**Closed** 2016-11-30 18:12 UTC
