### ISSUE TITLE
daily job to send edu-benefits report email

### ISSUE THREAD

**Issue by lihanli** [department-of-veterans-affairs/vets-api#227] opened 2016-10-06 18:21 UTC

**Comment by jcmeloni** [comment] 2016-10-13 15:28
@akainic Is this part of the Veterans Day requirements? Thanks!

**Comment by akainic** [comment] 2016-10-14 18:57
@jcmeloni yes it is! Needs to be done before education form launches

**Comment by akainic** [comment] 2016-10-17 18:38
Closing, duplicate of #237

**Closed by akainic** 2016-10-17 18:38 UTC
Labels: edu-benefits, veterans-day
