### ISSUE TITLE
Olive Branch is preventing rails console from starting.

### ISSUE THREAD

**Issue by mphprogrammer** [department-of-veterans-affairs/vets-api#72] opened 2016-09-09 14:23 UTC
Traced error to this line in application.rb:
`config.middleware.use "OliveBranch::Middleware"`

The error:
```
/Users/v/.rvm/gems/ruby-2.3.0@sm-api/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/stack.rb:112:in `push': can't modify frozen Array (RuntimeError)
           from /Users/v/.rvm/gems/ruby-2.3.0@sm-api/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/stack.rb:112:in 'use'
           from /Users/v/Dsva/vets-api/config/application.rb:43:in '<class:Application>'
           from /Users/v/Dsva/vets-api/config/application.rb:18:in '<module:VetsAPI>'
           from /Users/v/Dsva/vets-api/config/application.rb:17:in '<top (required)>'
           from /Users/v/.rvm/gems/ruby-2.3.0@sm-api/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in 'require'
           from /Users/v/.rvm/gems/ruby-2.3.0@sm-api/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in 'block in require'
           from /Users/v/.rvm/gems/ruby-2.3.0@sm-api/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in 'load_dependency'
           from /Users/v/.rvm/gems/ruby-2.3.0@sm-api/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in 'require'
           from /Users/v/.rvm/gems/ruby-2.3.0@sm-api/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:141:in 'require_application_and_environment!'
           from /Users/v/.rvm/gems/ruby-2.3.0@sm-api/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:67:in 'console'
           from /Users/v/.rvm/gems/ruby-2.3.0@sm-api/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in 'run_command!'
           from /Users/v/.rvm/gems/ruby-2.3.0@sm-api/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in '<top (required)>'
           from /Users/v/.rvm/gems/ruby-2.3.0@sm-api/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in 'require'
           from /Users/v/.rvm/gems/ruby-2.3.0@sm-api/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in 'block in require'
           from /Users/v/.rvm/gems/ruby-2.3.0@sm-api/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in 'load_dependency'
           from /Users/v/.rvm/gems/ruby-2.3.0@sm-api/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in 'require'
           from /Users/v/Dsva/vets-api/bin/rails:10:in '<top (required)>'
           from /Users/v/.rvm/gems/ruby-2.3.0@sm-api/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in 'load'
           from /Users/v/.rvm/gems/ruby-2.3.0@sm-api/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in 'block in load'
           from /Users/v/.rvm/gems/ruby-2.3.0@sm-api/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in 'load_dependency'
           from /Users/v/.rvm/gems/ruby-2.3.0@sm-api/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in 'load'
           from /Users/v/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
           from /Users/v/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
           from -e:1:in '<main>'

**Comment by lihanli** [comment] 2016-09-09 16:06
which branch is this on? i can't reproduce on master

**Comment by saneshark** [comment] 2016-09-09 16:58
@mphprogrammer do you mind adding steps to reproduce? Where specifically did you add a binding.pry that caused the issue?

**Comment by saneshark** [comment] 2016-09-20 20:50
@mphprogrammer I'm closing this issue because you mentioned today that it is working for you.

**Closed by saneshark** 2016-09-20 20:50 UTC
