### ISSUE TITLE
Update findCandidate MHV (staging)

### ISSUE THREAD

**Issue by robbiethegeek** [department-of-veterans-affairs/vets-api#286] opened 2016-10-17 20:35 UTC
update the regex on line 76.

mhv_id: select_extension(ids, /^\w+\^PI\^200MHV\^\w+\^\w+$/, CORRELATION_ROOT_ID)

To support Staging pattern

**Comment by kreek** [comment] 2016-10-18 00:02
duplicate of https://github.com/department-of-veterans-affairs/vets-api/issues/281

**Closed by kreek** 2016-10-18 00:02 UTC
Labels: in progress
